[package]
name = "rust_image_fiddler"
version = "0.1.0"
edition = "2021"

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
fltk = "^1.4"
image = "0.25.2"
quantizr = "1.4.2"
rayon = "1.10.0"
