[package]
name = "rust_image_fiddler"
version = "0.1.0"
edition = "2021"

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
fltk = { version = "^1.4", features = ["fltk-bundled"] }
image = "0.25.2"
png = "0.17.13"
quantizr = "1.4.2"
rayon = "1.10.0"
rosc = "0.10.1"
